databases:
  - name: openmemory-db
    databaseName: openmemory
    plan: free
    # Enable pgvector extension
    postgresMajorVersion: "15"

services:
  - type: web
    name: openmemory-mcp
    runtime: docker
    dockerContext: .
    dockerfilePath: ./openmemory/api/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: openmemory-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false # You'll need to set this in Render dashboard
      - key: API_KEY
        sync: false # Same as OPENAI_API_KEY
      - key: USER
        value: "default-user" # You can change this to your desired user ID
      - key: DEFAULT_APP_ID
        value: "openmemory-app"
      # pgvector Configuration
      - key: VECTOR_STORE_PROVIDER
        value: "pgvector"
      - key: PGVECTOR_DATABASE_URL
        fromDatabase:
          name: openmemory-db
          property: connectionString
      # Additional configuration
      - key: PORT
        value: "8765" 